### PR TITLE
DoD: check print preview when called for

### PR DESCRIPTION
**Pull request by henrik**
- [x] HN
- [x] JK
- [x] TS
- [x] AR
- [ ] KP (if back)

### CODE REVIEW

**Comment by tskogberg** [comment]
:fist:

**Comment by soma** [comment]
I wonder if it makes sense to have this in the dod? :racehorse:

**Comment by henrik** [comment]
@soma I kind of think of it as a checklist: "I think I'm done – let's see if I forgot anything". We have other very similar things in the DoD currently. But I'm open to putting it elsewhere – any ideas?

**Comment by henrik** [comment]
@soma Maybe this would make more sense in the front-end docs I was planning on adding? Then the DoD could just link to it, maybe (or not refer to it at all).

**Comment by henrik** [comment]
@Lavinia We'll merge this since you're not here; let us know if you disagree.

**Pull request merged**
