### PR TITLE
Add 'Shape Up' section to Process page

### PR DESCRIPTION
**Pull request by henrik**

### CODE REVIEW

**Review by frederfred — APPROVED** [review]

**Review by p-wall — CHANGES_REQUESTED** [review]
Other changes include: we're not shaping as much, and the betting is done before shaping

**Comment by henrik** [comment]
Thanks! Yeah, that felt more in flux so I intentionally didn't include anything about the shaping part. But I could give it a stab!

**Comment by henrik** [comment]
Gave it a shot 🤷‍♂️

**Review by p-wall — APPROVED** [review]

**Comment by tskogberg** [comment]
Should it mention something about our product team? So it's more clear how we work together.

**Review by tskogberg — APPROVED** [review]

**Review by olleolleolle — APPROVED** [review]
Nice to have included!

**Comment by henrik** [comment]
@tskogberg 

> Should it mention something about our product team? So it's more clear how we work together.

Hm, could you give an idea of what kind of mentions you had in mind?

**Comment by p-wall** [comment]
It's been a week, I'll merge

**Pull request merged**
