### PR TITLE
This is a style I have adopted without thinking about it much. I thin…

### PR DESCRIPTION
**Pull request by soma**
…k it makes sense in a way, because it groups the relevant information together with the code you are looking at. It is also kind of a smell though, since this

implies that you have such a big class that you need this grouping. But it is a fact that we often end up with classes big enough to make it convenient to put group the method and constant together.

What do you think?

### CODE REVIEW

**Comment by henrik** [comment]
Hm, what is the value you see in a "local constant"? That it's less magic than inlining the value, because it can be named and documented more clearly?

I wonder if we should presume to know where a "local constant" will be used. You had some actual example of this, with a magic number that seemed like it might also be reusable in views, IIRC. If there's any chance that constants are useful elsewhere, putting them at the the top makes that easier.

I'd be fine with allowing these constants for those who prefer that, but I'd rather not have this phrased as a rule. Maybe we could say something to the effect of "constants belong at the top, but if they have a smaller scope, feel free to move them down"? I'd happily :+1: that.

**Comment by soma** [comment]
Yes, the example is here: https://github.com/barsoom/auctionet/commit/45d9cc0be5412d454c296de7ebdc59fe1182f49b#commitcomment-14899694

**Comment by henrik** [comment]
Aha. In that particular case I think I might just document the default (like you did, excellently) but not extract it. Since it's only used in one place and you are able to document it in that one place.

Extracting named constants as a way of explaining magic values is great when they're reused (and then it probably makes sense to put the constant up top) but I don't think I'd do that here, personally.

**Comment by joakimk** [comment]
About https://github.com/barsoom/auctionet/commit/45d9cc0be5412d454c296de7ebdc59fe1182f49b#commitcomment-14899694 I think the previous version was easier to read. We can still have a comment that explains what the default does without having a constant?

**Comment by soma** [comment]
Yeah I agree. I guess it just stings a bit for me to have a value there, but you are right, extracting it like that does not really help that much.

**Pull request closed without merging**
