### PR TITLE
Styleguide: Explicit branches

### PR DESCRIPTION
**Pull request by henrik**
The last reviewer to approve this (if we all approve) can please merge and close the PR.

Based on this discussion: https://github.com/barsoom/auctionet/commit/59b1d684c79075b1784c31fa1c8df7fa05eef279#r25812409

### CODE REVIEW

**Comment by victorarias** [comment]
Hello!

In principle I'm not against this, however I also don't see the value on it and I'm afraid that making it a "rule" can be stressful if I have to consistently go back to change it, especially without automatic linting.

Do you have any reading material on the benefits of this? Or is it possible to verify that with a linter?

**Comment by henrik** [comment]
I agree automatic linting would be great. Maybe the topics of automatic linting and to what extent we should "have to" go back and fix things etc is a wider discussion that we could have elsewhere (maybe retro?) since it applies to all review, not just this proposal. Fair enough?

About this specific suggestion: With code like

``` ruby
def my_method
  if something
    1
  end
end
```

there is an implicit `else: nil`. Since it's implicit, you won't see it when scanning the code. You need to run the code in your head (and consider this quirk of Ruby) to "see" it. So e.g. someone who wants to call this method may look at it quickly and miss that they have to handle a nil.

Generally, I feel that explicit is preferably to implicit, all other things equal. In this situation, I'm not aware of any strong reasons to go with the more implicit version. It's a little less typing, but only because you leave it to frail humans to expand the implicit "else" branch in their heads every time :)

**Comment by victorarias** [comment]
I mentioned linting on this topic because I consider it as a good solution to follow guidelines that aren't natural for me, which is the case here.

> In this situation, I'm not aware of any strong reasons to go with the more implicit version.

My main concern is having to remember this since this doesn't feel idiomatic. I have no problem following coding standards that I don't see the value but I'm afraid I won't remember them. If I keep forgetting them it would be frustrating to everyone.

> Generally, I feel that explicit is preferably to implicit, all other things being equal.

I agree but when the implicitness is part of the language I prefer to stick with the language design. There are a lot of cases of implicitness around returning values from functions in Ruby.

**Comment by henrik** [comment]
I wholeheartedly agree about linting. There are many reasons it would be valuable to have, independent of this specific style rule.

I think you are right that the implicit else branches are idiomatic. I prefer for us to follow idioms except where we see benefits in doing it differently – as I do here.

It comes down to that I find the explicit branches easier to see at a glance, and harder to miss, and thus I assume it makes code a little faster to read and less error prone to work with. But I don't have hard data or any specific examples to offer up at this time. I suspect I had actual examples at the time years ago that I decided I preferred to be explicit here. I could keep an eye out and let you know.

What do the rest of you think?

**Comment by henrik** [comment]
Oh yeah, another benefit is that it encourages us (by providing an obvious place) to document why we have a nil case. This is a good recent example: https://github.com/barsoom/auctionet/commit/9f5c99c55655e3d94337d3a6c30d4c48b41dfce5

**Comment by tskogberg** [comment]
As for the linter part, I'm all for that. We could run that automatically on CI and I think it would save us some review time. I know that many uses: [rubocop](https://github.com/bbatsov/rubocop).

When it comes to implicit branching (single conditions), I find them handy. I did a fast grep and I see that we do use it quite a lot. I guess the most important thing is that we have tests that covers them (that will tell others that you have thought about that branch and you will feel more confident).

**Comment by henrik** [comment]
@tskogberg Could you give a few examples of where we are implicit and you like it? I want to be clear that I'm only advocating explicit `else nil` for return values (from methods as well as blocks).

So I'm fine with

``` ruby
def method
  do_it if something

  :my_return_value
end
```

but not with

``` ruby
def method
  123 if something
end
```

**Comment by henrik** [comment]
@tskogberg @victorarias Any further thoughts? Do you still feel you do not want this styleguide rule after my clarification that it's only about return values? It doesn't seem like anyone else wants to weigh in, so if you're still against I will close this without action.

**Comment by victorarias** [comment]
My position stands: I would prefer to avoid adding more non-idiomatic rules without automatic linting to avoid negative review comments and having to go back to fix them.

I don't think it's healthy for one individual to be able to block a style that everyone else agrees on, so if I'm the only one on this side, feel free to merge this. I ask you (and the rest of the team) to consider implementing Rubycop (or something similar) before adding more non-idiomatic rules in the future.

**Comment by henrik** [comment]
@victorarias Thank you. I'm looking into a good way to get a hosted per-commit Rubocop ([Codacy](https://www.codacy.com/) seems the only option unless we roll our own), though I don't know how easy this specific rule would be to implement.

I'll wait a few more days to see if @joakimk and @Lavinia would please weigh in, and if @tskogberg has further comments after the clarification.

**Comment by dentarg** [comment]
> hosted per-commit Rubocop

Don't you want Rubocop to run locally, so you can catch errors before commit and push?

**Comment by henrik** [comment]
@dentarg: I'm looking into that as well, though I did not mention it here :) A pre-commit hook would add about 1 second runtime to every commit, which I'm not sure about. Do you have any experience or suggestions about good ways of running it?

**Comment by joakimk** [comment]
@henrik Have you considered running rubocop post-commit, async and only print messages if rules are broken? That way you might have to do the fix as a separate commit but you don't have to wait for rubycop to run while committing.

**Comment by henrik** [comment]
@joakimk Yes, I edited that into my comment above right after posting it :D Might give that a shot next lab.

**Comment by dentarg** [comment]
> Do you have any experience or suggestions about good ways of running it?

I like how we do it at Twingly. We automatically run RuboCop after the specs have run successfully.

This is how our `Rakefile` look for one project where we use RuboCop:

```ruby
# frozen_string_literal: true

begin
  require "rspec/core/rake_task"

  RSpec::Core::RakeTask.new(:spec) do |task|
    seed = ENV.fetch("RSPEC_SEED") { "" }
    task.rspec_opts = "--order rand:#{seed}"
  end
rescue LoadError
  warn "Could not require RSpec gem"
end

begin
  require "rubocop/rake_task"

  desc "Run RuboCop"
  RuboCop::RakeTask.new(:rubocop).tap do |task|
    task.options = %w[--parallel]
  end
rescue LoadError
  warn "Rakefile could not require RuboCop gem"
end

task default: %i[spec rubocop]
```

As our specs takes many seconds to run, we are not that concerned about one extra second for RuboCop. :) 

During development, we use rspec [focus filtering](https://relishapp.com/rspec/rspec-core/v/3-7/docs/filtering/filter-run-when-matching) to lower the time it takes to run specs. And RuboCop with [rubocop-rspec-focused](https://github.com/lovewithfood/rubocop-rspec-focused) helps us catch commits that accidentally left specs focused.

**Comment by henrik** [comment]
@dentarg Thank you! That's interesting. I made a githook, though it's still a bit rough and WIP: https://gist.github.com/henrik/e8583343ce0347db7f2480f46cf4fdce

**Comment by tskogberg** [comment]
@henrik I have no objections. And I like @victorarias idea about adding Rubocop to catch things like this.

**Comment by dentarg** [comment]
@henrik Cool! How do you distribute such githook scripts to all users of the git repo? Is it possible to do it via the repo (e.g. github)?

**Comment by henrik** [comment]
@dentarg Yes, we have a ".githooks" dir in our monolith repo, but IIRC there's currently no automation to set up symlinks to .git/hooks.

So Victor is OK with this rule if no one else objects to it. Tomas does not object. Albert has approved the PR. @joakimk and @Lavinia, we are waiting for your response.

**Comment by joakimk** [comment]
I like being explicit about returns. About the githooks we can automate that kind of a thing across all projects using our devbox tooling.

**Comment by henrik** [comment]
@Lavinia Up to you now. If you agree, please merge. If you disagree, please close. If it's complicated, please write a comment :D 

If I haven't heard anything in about a week I'll merge and we can revert if needed.

**Pull request merged**
