### PR TITLE
Simplify consensus model.

### PR DESCRIPTION
**Pull request by joakimk**
- [x] Henrik
- [x] Jocke
- [x] Albert
- [x] Tomas

### CODE REVIEW

**Comment by henrik** [comment]
Good idea.

> If you haven't voted after two weeks, it counts as a non vote.

The description doesn't explicitly say how to vote "no". And if I ask follow-up questions but don't vote for two weeks, is that a non-vote?

**Comment by soma** [comment]
Yes, It should state how to disagree with the PR.

**Comment by soma** [comment]
Also, how do I even disagree to this PR? Oh the madness!

**Comment by joakimk** [comment]
You disagree by commenting and not checking your checkbox?

**Comment by henrik** [comment]
Explicit is better than implicit. Maybe something like "If you veto or need more discussion, say so in a comment. If you haven't weighed in after two weeks …"? "weighed in" as opposed to "voted".

**Comment by soma** [comment]
Yes, please add something simple like @henrik suggests.

**Comment by joakimk** [comment]
Added the thing that henrik suggested.

**Comment by henrik** [comment]
Excellent! @tskogberg, merge if you're happy!

**Pull request merged**
