### PR TITLE
Styleguide, JS: 'if ()', not 'if()'

### PR DESCRIPTION
**Pull request by henrik**
- [x] Henrik
- [x] Jocke
- [x] Albert
- [x] Tomas

### CODE REVIEW

**Comment by henrik** [comment]
Per discussion: https://github.com/barsoom/auctionet/commit/a6554580e7ac6aae6dc7f15bf401c6358566baa0#diff-8263227b83170a518f96c4589f57ffd3R16

**Comment by henrik** [comment]
Crockford is with me: http://javascript.crockford.com/code.html#if%20statement

**Comment by henrik** [comment]
JSLint doesn't explicitly seem to make a rule here but all their code examples have the space: http://www.jslint.com/lint.html

**Comment by joakimk** [comment]
This is one of those stylistic choices I’ve kept to for more than 10 years.

I’d prefer if we do `if(foo)`, just as we do `bar(foo)` and not `bar (foo)` for method calls.

I guess I’ll have to agree to use the js-convention in javascript, though I’ll very likely do it wrong many times since I’ve had this style for more than a decade :)

**Comment by henrik** [comment]
@joakimk Thank you! I know it sucks to change a deeply-rooted habit :) :fish: :fishing_pole_and_fish:

**Comment by henrik** [comment]
@soma Only waiting on you.

**Comment by henrik** [comment]
@soma If you're the last person to OK it, feel free to merge :) I'll do it now though.

**Pull request merged**
