### PR TITLE
Don't "broken window" old projects

### PR DESCRIPTION
**Pull request by henrik**
The actual text change isn't very strongly phrased: the purpose of this pull request is mostly to have somewhere to discuss what we want to do about legacy CSS. The exact phrasing in the README isn't that important, maybe.

So: should we keep piling on anything-goes CSS in old projects, e.g. Auctionet admin and Bookie? Or should we try to write any new CSS in the new style (BEM etc)?

### Expressed an opinion (not necessarily "a vote for this"):

- [x] HN
- [x] KP
- [x] AR
- [x] VA
- [x] JK
- [x] TS

### CODE REVIEW

**Comment by henrik** [comment]
I think we should aim to write new CSS in the new style. Here are some reasons:

* Everyone who will be touching the Auctionet front-end needs to learn it anyway.

* BEM attempts and mostly succeeds (IMO) in solving several pain points like selector collisions, specificity wars, clarifying which selectors go together to form a whole. Why not get that for new additions to old systems?

**Comment by henrik** [comment]
@soma @victorarias @tskogberg @joakimk @Lavinia Your thoughts?

**Comment by Lavinia** [comment]
I agree with @henrik.

Does this mean we also change old CSS when we stumble upon it?

**Comment by henrik** [comment]
> Does this mean we also change old CSS when we stumble upon it?

I would say it depends – if we're rewriting big parts of an admin view, it's probably a good idea. If we're just making a tiny change and rewriting the whole thing would mean a lot of work, it's probably not worth it. Much like with the other styleguide rules: we don't always rewrite e.g. RSpec syntax if we touch a test file, but if we touch all of it we probably do.

**Comment by soma** [comment]
I agree that when the cost is relatively low, we should just do the "new thing". But sometimes the cost of rewriting or reworking stuff towards new standards is high, and is not worth the effort.

This line is hard to define since it depends on various factors (how mature the "new way" is, how much similar code there is, proficiency of the developer... etc).

If we are to start migrating something like the admin css to a new style, I think we need to first make an effort to put in a skeleton or something to build from and then present/document this.

It should not be put on the person making a minor change to something to figure out how it all fits together, for this to work there needs to be clear guidelines. Often the task at hand is urgent and complex in it self.

**Comment by henrik** [comment]
Maybe the biggest obstacle here is that everyone isn't familiar with the new style – I hope to prepare a presentation next lab days.

Good point about putting in a skeleton. I'll look into that now.

**Comment by henrik** [comment]
Added comments to the top of the admin.scss file: https://github.com/barsoom/auctionet/commit/4d143ef483fb0f91927a6502df763b624968b7a8

Did not add a skeleton of files. We already have an admin/components directory, and other directories can trivially be added as needed as outlined in the styleguide.

**Comment by henrik** [comment]
@joakimk @victorarias Any thoughts on this?

**Comment by joakimk** [comment]
I think we'll see how it goes.

**Comment by victorarias** [comment]
I have a similar opinion to @soma. It would be hard for me to develop a new page on the admin writing BEM-style CSS right now, with no foundation. @henrik 's presentation would probably go a long way of making me more confortable.
That being said, I agree we should follow, on existing projects, a new style that has proven to yield a better CSS structure.

**Pull request merged**
