### PR TITLE
Add rule to styleguide voting

### PR DESCRIPTION
**Pull request by tskogberg**
This will speed up the pull requests a bit. We can tweak the number of weeks if needed.

What do you guys think?

- [x] HN
- [ ] KP
- [x] AR
- [x] TS
- [x] JK

### CODE REVIEW

**Comment by henrik** [comment]
Hm.

One tiny language thing: "abstain" is something intentional (something formal, even). What we want is probably "if someone doesn't vote" – we don't really care if it's intentional, right?

I wonder if it will become a problem that this could be abused around vacation time. I don't think anyone would intentionally do that, but it would be weird if something goes into the devbook while person X is on a four week summer vacation, and they hate it.

I would also suggest a shorter period – two weeks?

Maybe we could do something this. Possibly overcomplicated, but it covers all of the things, I think… :)

> If you haven't voted after two weeks, it counts as a :fist: vote. If no one else is opposed, the pull request may be merged without your vote, though you should be notified in a comment.
>
> After that, you get one week to change your vote, if you want the merge to be reverted. If you've been on vacation or sick, the week starts when you get back.
>
> If you haven't changed your vote after six weeks, the change sticks, even if you've been away – the devbook must go on. If you want to change it then, make a new pull request.

**Comment by tskogberg** [comment]
Yes, that is more clear. I'll add that. :+1:

**Comment by soma** [comment]
Why even have that text? I agree having a timeout and that implying "dont care - do what you want" .. is good. But why have rules after that? You can just submit a PR removing the change you suddenly did not like and state your case? Simpler to just have the same process I think?

**Comment by henrik** [comment]
@soma You mean, why not just have the first paragraph?

It's much harder to get something removed (others can veto you) than to prevent something from being added (you can veto), so that's why – would suck to come back from vacation and something you'd wanted to veto got in.

But I'd be OK with "just" adding the first paragraph. If it turns out we need to complicate it, we can always do so later.

**Comment by henrik** [comment]
Attempt to rephrase:

> If you haven't voted after two weeks, it counts as a :fist: vote. If no one else is opposed, the pull request may be merged without your vote, though you should be notified in a comment.
>
> If you missed the vote and want to veto it after the fact, we will revert it. But if enough time has passed we encourage you to instead make a new pull request.

**Comment by soma** [comment]
funkar

**Comment by joakimk** [comment]
funkar

**Comment by henrik** [comment]
@tskogberg Merge if you're happy with the rephrase.

**Pull request merged**
