### PR TITLE
Add private class method to the class layout

### PR DESCRIPTION
**Pull request by tskogberg**
Good idea?

- [x] HN
- [ ] KP
- [x] TS
- [ ] AR
- [ ] JK
- [ ] VA

### CODE REVIEW

**Comment by henrik** [comment]
Clever to just put it in this section!

**Comment by henrik** [comment]
Merging after 2+ weeks per our rules. @Lavinia, @soma, @joakimk, @victorarias

**Comment by joakimk** [comment]
Oh, well... adding my check to this after the fact then :)

**Comment by joakimk** [comment]
I don't think we get notified of new pull reqs in the mail?

**Comment by henrik** [comment]
I do, but maybe we have different notification settings or ownership.

**Pull request merged**
