### PR TITLE
Styleguide: Put a last-run date in scripts

### PR DESCRIPTION
**Pull request by henrik**
I'm currently renaming something and it's very hard for me to tell which scripts are worth updating.

- [x] HN
- [ ] KP
- [ ] AR
- [x] JK
- [x] TS

### CODE REVIEW

**Comment by dentarg** [comment]
Interesting suggestion. Hope you don't mind an outsider commenting here.

Have you (the Barsoom team) discussed this internally and this is just agreeing on the wording, or is this PR for discussing the practice suggested? (I have some comments/question, but I will hold of on them, as I'm afraid of maybe skewing your views on the matter.)

**Comment by henrik** [comment]
@dentarg Not at all, that's part of why we do this in public :) Would love to hear your views. If it influences our views, so much the better.

This is something I thought of and put here for approval or discussion. We try to decide on style issues (in a very wide sense) via PRs on this repo because before we had this process, we lost a lot of time on IRL discussions/debates in the dev room… :p But we can upgrade to another medium if we think that makes sense.

**Comment by Lavinia** [comment]
What exactly does this mean? That we only change scripts of a certain age? If so, where do we draw the line. I can think of a few scripts that we use only once or maybe twice a year, so I guess all older than a year would be ok not to change? Please clarify so I can make an informed decision. :-)

**Comment by henrik** [comment]
Well, the idea with this PR would be to just provide more data – I don't want to prescribe exactly how that data should be used. But to give an idea, I think I would have used it to remove any script not run in say the last 2 years, to err on the side of keeping too much rather than too little.

**Comment by joakimk** [comment]
I like it. I hope we remember to do this though.

**Comment by soma** [comment]
We could also just not update anything in the scripts folder, and see how that affects us, because I suspect that it will not have a huge impact at all. If things are changed down the line and you use an old script, at least I will not be surprised that the script is no longer working 100%, and in the rare case that you actually need to change it, it is better to just take the cost there and then.

But we should maybe just put all scripts that we _know_ will be run in the future in a separate folder, which also would have the benefit of us having more strict rules about how we work with them. If they are truly in continuous use, we should have tests etc.

**Comment by dentarg** [comment]
Alright, here are my comments on this suggestion.

I like to have information, therefore I welcome the information of knowing when a script last ran. But I also dislike making humans do things they aren't good that, which is, to remember to do something. So we create lists: do this, do that. But as humans will forget sometimes anyway.

So I think the `Last run` comment wont always be accurate. Will it then be able to help with the goal of knowing which scripts to maintain and which to remove?

If not, maybe then we are better of without the `Last run` comment.

And of course, we can always automate it (the computer always remembers to do what it is told to do). But then you have to figure out [if it is worth it](https://xkcd.com/1205/).

Looking forward to observe the outcome here. :)

**Comment by soma** [comment]
@dentarg wow nice to have outsider feedback! Much appreciated!

Good points there. Although I guess it will at least be accurate that it was run at the "last run", which might be good enough?

But as I said before, I think we are better off just ignoring any maintenance on these scripts, and if they are run often enough, we will have to update them. And if someone notices they have to run an outdated script, maybe at that time make sure it is in the "recurring scripts folder" with the added benefit of making sure it has tests etc. IE promote the script there and then.

The whole maintenance situation with "one-off-ish" scripts to extract or modify data is messy now, but I still feel it is useful to have them there in the codebase. I noticed someone removed a script they wrote, with the comment "it is still in git". At least I do not check git history for lost files when trying to see if we have a script that does something someone wants.. so I think putting them there is generally a bad thing. But this is another discussion ofc, but it is the same domain of script maintenance :)

**Comment by tskogberg** [comment]
I'd say that if we see a value of having this we should also make sure to automate it. We could have a hook that stores info in redis and/or updates the script file.

**Comment by henrik** [comment]
@tskogberg That would be great, though I'm not sure how we'd hook that in. Sometimes we use Rails runner, sometimes it's plain Ruby scripts. Sometimes I'll copy-paste into a console since that's often the most convenient way.

**Comment by tskogberg** [comment]
@henrik That is true and yes that makes it a bit harder and the thing I was thinking about won't work for all those cases.

In general, should we merge this or? It's been hanging here for quite some time… 😄

**Comment by soma** [comment]
I vote for not merging this, and instead schedule a meeting or retro where we sort out how we want to handle "scripts" in our codebase, for reasons stated above.

**Comment by henrik** [comment]
Yes, this doesn't seem like something we can merge as-is. I'll close the issue.

**Pull request closed without merging**
