### PR TITLE
Styleguide: Document ID for anchor

### PR DESCRIPTION
**Pull request by henrik**
- [x] HN
- [x] KP
- [x] TS
- [x] AR
- [x] JK
- [x] VA

### CODE REVIEW

**Comment by Lavinia** [comment]
Sounds like a good idea.

**Comment by henrik** [comment]
Hm. I wonder if this is too non-stylish for a styleguide. It's definitely a practise that I would like to propose, and it's something I'll mention in code review, but maybe the styleguide becomes too big if it has a ton of "recommended practise" and not just things like quote style?

**Comment by victorarias** [comment]
I like the practise - I already removed one anchor by mistake because it wasn't easy to see that it was still being used.
I'm not sure about  the question "does it fit the styleguide?".

**Comment by victorarias** [comment]
By being not sure I'm making no judgement at all.

@henrik would changing the organization of the styleguide help in our opinion? Maybe moving to a different file "recommended practise" and then linking it from the styleguide.

**Comment by tskogberg** [comment]
Why not just give it a prefix or suffix? `anchor_snake` or `snake_anchor`. And add that to the devbook. Could be clear enough so you don't need a comment.

**Comment by Lavinia** [comment]
I like @tskogberg idea. No need for comments, self documenting code:-).

**Comment by henrik** [comment]
@victorarias I considered splitting out a file. Might be a hard limit to draw though. I'm undecided on whether it's worth having two buckets.

@tskogberg I considered that (since this is very similar to the js- and test- prefixes), but since the IDs become part of URLs, that means URLs become a little uglier. /foo.html#thing_anchor looks a bit weird to me :) I like that it would be self-documenting and consistent with js- and test-, but my preference is for the comment if that keeps the anchor slightly prettier :)

**Comment by henrik** [comment]
Merging since Tomas said I could :)

**Comment by henrik** [comment]
Closing ticket since it's merged but please don't see it as a "I'm right, discussion closed" thing. The comment is better than nothing, and please do keep discussing the prefix/suffix thing if you think it has merit.

**Pull request merged**
