### PR TITLE
Use %w[] and friends with square brackets

### PR DESCRIPTION
**Pull request by henrik**
- [x] HN
- [x] TS
- [x] AR
- [x] JK

(Not Kim since she won't be back within 2 weeks.)

### CODE REVIEW

**Comment by joakimk** [comment]
I think it's pretty conventional to do %{} and %w{}, that's how I've always done them.

**Comment by henrik** [comment]
> I think it's pretty conventional to do %{} and %w{}, that's how I've always done them. 

This PR doesn't cover `%{}` (since it doesn't return an array).

I've no idea what is conventional with `%w[]`. I prefer square brackets for the stated reason but if you feel differently that's perfectly valid, of course.

**Comment by joakimk** [comment]
I don't feel a need for this, but if you often confuse %w{ } for a hash, then maybe.

**Comment by joakimk** [comment]
I always write them like that btw.

**Comment by henrik** [comment]
I don't confuse them with hashes, but it takes me a little longer to tell them apart from `%q{}` strings. Feels that way, at least. I haven't A/B tested…

**Comment by henrik** [comment]
@joakimk Is that a veto, btw? Want to know what to do about this PR.

@soma Any opinion?

**Comment by soma** [comment]
Not really. Although I would remember a rule better if all the %xyz-methods used the same notation...

I think I've mostly gone with () up until now, but I rarely use them and if anyone wants a guideline, im fine with it.

**Comment by henrik** [comment]
I don't think the same notation makes sense for all of them. I like `%[]` for the ones that produce arrays and `%{}` for the rest (though I've probably used it inconsistently with `%()`).

We could expand this rule to recommend `%{}` or `%()` for non-array things if we think that'd help. Personally I only care semi-strongly about the array thing since I've found that it trips me up slightly when done "wrong". I don't need a rule for the rest.

@joakimk Let me know your position so I know whether to merge or close (or something else).

**Comment by joakimk** [comment]
I would not use `%()` because I would confuse that with `()`.

I guess we can have a rule to do %[a b c]. I'm prefectly happy with `%w{a b c}` though.

**Comment by henrik** [comment]
Alright, I'm interpreting this as a yes from everyone. Let me know if that's wrong.

**Pull request merged**
